/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReadingsRouteImport } from './routes/api/readings'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedSupplierShopRouteImport } from './routes/_authenticated/supplier-shop'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedSuppliersIndexRouteImport } from './routes/_authenticated/suppliers.index'
import { Route as AuthenticatedDevicesIndexRouteImport } from './routes/_authenticated/devices.index'
import { Route as ApiPublicReadingsRouteImport } from './routes/api/public/readings'
import { Route as ApiIrrigationDecisionRouteImport } from './routes/api/irrigation/decision'
import { Route as ApiCommandsNextRouteImport } from './routes/api/commands/next'
import { Route as ApiAdviceLatestRouteImport } from './routes/api/advice/latest'
import { Route as AuthenticatedSuppliersIdRouteImport } from './routes/_authenticated/suppliers.$id'
import { Route as AuthenticatedDevicesNewRouteImport } from './routes/_authenticated/devices.new'
import { Route as AuthenticatedDevicesIdRouteImport } from './routes/_authenticated/devices.$id'
import { Route as ApiPublicIrrigationDecisionRouteImport } from './routes/api/public/irrigation/decision'
import { Route as ApiPublicDevicesRegisterRouteImport } from './routes/api/public/devices/register'
import { Route as ApiPublicDevicesIngestRouteImport } from './routes/api/public/devices/ingest'
import { Route as ApiPublicDevicesConfigRouteImport } from './routes/api/public/devices/config'
import { Route as ApiPublicDevicesCommandsRouteImport } from './routes/api/public/devices/commands'
import { Route as ApiPublicDevicesAckRouteImport } from './routes/api/public/devices/ack'
import { Route as ApiPublicCommandsNextRouteImport } from './routes/api/public/commands/next'
import { Route as ApiPublicAdviceLatestRouteImport } from './routes/api/public/advice/latest'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadingsRoute = ApiReadingsRouteImport.update({
  id: '/api/readings',
  path: '/api/readings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupplierShopRoute =
  AuthenticatedSupplierShopRouteImport.update({
    id: '/supplier-shop',
    path: '/supplier-shop',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersIndexRoute =
  AuthenticatedSuppliersIndexRouteImport.update({
    id: '/suppliers/',
    path: '/suppliers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevicesIndexRoute =
  AuthenticatedDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicReadingsRoute = ApiPublicReadingsRouteImport.update({
  id: '/api/public/readings',
  path: '/api/public/readings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIrrigationDecisionRoute = ApiIrrigationDecisionRouteImport.update({
  id: '/api/irrigation/decision',
  path: '/api/irrigation/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommandsNextRoute = ApiCommandsNextRouteImport.update({
  id: '/api/commands/next',
  path: '/api/commands/next',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdviceLatestRoute = ApiAdviceLatestRouteImport.update({
  id: '/api/advice/latest',
  path: '/api/advice/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuppliersIdRoute =
  AuthenticatedSuppliersIdRouteImport.update({
    id: '/suppliers/$id',
    path: '/suppliers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevicesNewRoute = AuthenticatedDevicesNewRouteImport.update({
  id: '/devices/new',
  path: '/devices/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesIdRoute = AuthenticatedDevicesIdRouteImport.update({
  id: '/devices/$id',
  path: '/devices/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicIrrigationDecisionRoute =
  ApiPublicIrrigationDecisionRouteImport.update({
    id: '/api/public/irrigation/decision',
    path: '/api/public/irrigation/decision',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDevicesRegisterRoute =
  ApiPublicDevicesRegisterRouteImport.update({
    id: '/api/public/devices/register',
    path: '/api/public/devices/register',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDevicesIngestRoute = ApiPublicDevicesIngestRouteImport.update({
  id: '/api/public/devices/ingest',
  path: '/api/public/devices/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDevicesConfigRoute = ApiPublicDevicesConfigRouteImport.update({
  id: '/api/public/devices/config',
  path: '/api/public/devices/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDevicesCommandsRoute =
  ApiPublicDevicesCommandsRouteImport.update({
    id: '/api/public/devices/commands',
    path: '/api/public/devices/commands',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDevicesAckRoute = ApiPublicDevicesAckRouteImport.update({
  id: '/api/public/devices/ack',
  path: '/api/public/devices/ack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCommandsNextRoute = ApiPublicCommandsNextRouteImport.update({
  id: '/api/public/commands/next',
  path: '/api/public/commands/next',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdviceLatestRoute = ApiPublicAdviceLatestRouteImport.update({
  id: '/api/public/advice/latest',
  path: '/api/public/advice/latest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/home': typeof AuthenticatedHomeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/supplier-shop': typeof AuthenticatedSupplierShopRoute
  '/api/chat': typeof ApiChatRoute
  '/api/readings': typeof ApiReadingsRoute
  '/devices/$id': typeof AuthenticatedDevicesIdRoute
  '/devices/new': typeof AuthenticatedDevicesNewRoute
  '/suppliers/$id': typeof AuthenticatedSuppliersIdRoute
  '/api/advice/latest': typeof ApiAdviceLatestRoute
  '/api/commands/next': typeof ApiCommandsNextRoute
  '/api/irrigation/decision': typeof ApiIrrigationDecisionRoute
  '/api/public/readings': typeof ApiPublicReadingsRoute
  '/devices/': typeof AuthenticatedDevicesIndexRoute
  '/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/api/public/advice/latest': typeof ApiPublicAdviceLatestRoute
  '/api/public/commands/next': typeof ApiPublicCommandsNextRoute
  '/api/public/devices/ack': typeof ApiPublicDevicesAckRoute
  '/api/public/devices/commands': typeof ApiPublicDevicesCommandsRoute
  '/api/public/devices/config': typeof ApiPublicDevicesConfigRoute
  '/api/public/devices/ingest': typeof ApiPublicDevicesIngestRoute
  '/api/public/devices/register': typeof ApiPublicDevicesRegisterRoute
  '/api/public/irrigation/decision': typeof ApiPublicIrrigationDecisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/home': typeof AuthenticatedHomeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/supplier-shop': typeof AuthenticatedSupplierShopRoute
  '/api/chat': typeof ApiChatRoute
  '/api/readings': typeof ApiReadingsRoute
  '/devices/$id': typeof AuthenticatedDevicesIdRoute
  '/devices/new': typeof AuthenticatedDevicesNewRoute
  '/suppliers/$id': typeof AuthenticatedSuppliersIdRoute
  '/api/advice/latest': typeof ApiAdviceLatestRoute
  '/api/commands/next': typeof ApiCommandsNextRoute
  '/api/irrigation/decision': typeof ApiIrrigationDecisionRoute
  '/api/public/readings': typeof ApiPublicReadingsRoute
  '/devices': typeof AuthenticatedDevicesIndexRoute
  '/suppliers': typeof AuthenticatedSuppliersIndexRoute
  '/api/public/advice/latest': typeof ApiPublicAdviceLatestRoute
  '/api/public/commands/next': typeof ApiPublicCommandsNextRoute
  '/api/public/devices/ack': typeof ApiPublicDevicesAckRoute
  '/api/public/devices/commands': typeof ApiPublicDevicesCommandsRoute
  '/api/public/devices/config': typeof ApiPublicDevicesConfigRoute
  '/api/public/devices/ingest': typeof ApiPublicDevicesIngestRoute
  '/api/public/devices/register': typeof ApiPublicDevicesRegisterRoute
  '/api/public/irrigation/decision': typeof ApiPublicIrrigationDecisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/supplier-shop': typeof AuthenticatedSupplierShopRoute
  '/api/chat': typeof ApiChatRoute
  '/api/readings': typeof ApiReadingsRoute
  '/_authenticated/devices/$id': typeof AuthenticatedDevicesIdRoute
  '/_authenticated/devices/new': typeof AuthenticatedDevicesNewRoute
  '/_authenticated/suppliers/$id': typeof AuthenticatedSuppliersIdRoute
  '/api/advice/latest': typeof ApiAdviceLatestRoute
  '/api/commands/next': typeof ApiCommandsNextRoute
  '/api/irrigation/decision': typeof ApiIrrigationDecisionRoute
  '/api/public/readings': typeof ApiPublicReadingsRoute
  '/_authenticated/devices/': typeof AuthenticatedDevicesIndexRoute
  '/_authenticated/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/api/public/advice/latest': typeof ApiPublicAdviceLatestRoute
  '/api/public/commands/next': typeof ApiPublicCommandsNextRoute
  '/api/public/devices/ack': typeof ApiPublicDevicesAckRoute
  '/api/public/devices/commands': typeof ApiPublicDevicesCommandsRoute
  '/api/public/devices/config': typeof ApiPublicDevicesConfigRoute
  '/api/public/devices/ingest': typeof ApiPublicDevicesIngestRoute
  '/api/public/devices/register': typeof ApiPublicDevicesRegisterRoute
  '/api/public/irrigation/decision': typeof ApiPublicIrrigationDecisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/alerts'
    | '/chat'
    | '/dashboard'
    | '/finance'
    | '/home'
    | '/settings'
    | '/supplier-shop'
    | '/api/chat'
    | '/api/readings'
    | '/devices/$id'
    | '/devices/new'
    | '/suppliers/$id'
    | '/api/advice/latest'
    | '/api/commands/next'
    | '/api/irrigation/decision'
    | '/api/public/readings'
    | '/devices/'
    | '/suppliers/'
    | '/api/public/advice/latest'
    | '/api/public/commands/next'
    | '/api/public/devices/ack'
    | '/api/public/devices/commands'
    | '/api/public/devices/config'
    | '/api/public/devices/ingest'
    | '/api/public/devices/register'
    | '/api/public/irrigation/decision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/alerts'
    | '/chat'
    | '/dashboard'
    | '/finance'
    | '/home'
    | '/settings'
    | '/supplier-shop'
    | '/api/chat'
    | '/api/readings'
    | '/devices/$id'
    | '/devices/new'
    | '/suppliers/$id'
    | '/api/advice/latest'
    | '/api/commands/next'
    | '/api/irrigation/decision'
    | '/api/public/readings'
    | '/devices'
    | '/suppliers'
    | '/api/public/advice/latest'
    | '/api/public/commands/next'
    | '/api/public/devices/ack'
    | '/api/public/devices/commands'
    | '/api/public/devices/config'
    | '/api/public/devices/ingest'
    | '/api/public/devices/register'
    | '/api/public/irrigation/decision'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/alerts'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/home'
    | '/_authenticated/settings'
    | '/_authenticated/supplier-shop'
    | '/api/chat'
    | '/api/readings'
    | '/_authenticated/devices/$id'
    | '/_authenticated/devices/new'
    | '/_authenticated/suppliers/$id'
    | '/api/advice/latest'
    | '/api/commands/next'
    | '/api/irrigation/decision'
    | '/api/public/readings'
    | '/_authenticated/devices/'
    | '/_authenticated/suppliers/'
    | '/api/public/advice/latest'
    | '/api/public/commands/next'
    | '/api/public/devices/ack'
    | '/api/public/devices/commands'
    | '/api/public/devices/config'
    | '/api/public/devices/ingest'
    | '/api/public/devices/register'
    | '/api/public/irrigation/decision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiReadingsRoute: typeof ApiReadingsRoute
  ApiAdviceLatestRoute: typeof ApiAdviceLatestRoute
  ApiCommandsNextRoute: typeof ApiCommandsNextRoute
  ApiIrrigationDecisionRoute: typeof ApiIrrigationDecisionRoute
  ApiPublicReadingsRoute: typeof ApiPublicReadingsRoute
  ApiPublicAdviceLatestRoute: typeof ApiPublicAdviceLatestRoute
  ApiPublicCommandsNextRoute: typeof ApiPublicCommandsNextRoute
  ApiPublicDevicesAckRoute: typeof ApiPublicDevicesAckRoute
  ApiPublicDevicesCommandsRoute: typeof ApiPublicDevicesCommandsRoute
  ApiPublicDevicesConfigRoute: typeof ApiPublicDevicesConfigRoute
  ApiPublicDevicesIngestRoute: typeof ApiPublicDevicesIngestRoute
  ApiPublicDevicesRegisterRoute: typeof ApiPublicDevicesRegisterRoute
  ApiPublicIrrigationDecisionRoute: typeof ApiPublicIrrigationDecisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/readings': {
      id: '/api/readings'
      path: '/api/readings'
      fullPath: '/api/readings'
      preLoaderRoute: typeof ApiReadingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/supplier-shop': {
      id: '/_authenticated/supplier-shop'
      path: '/supplier-shop'
      fullPath: '/supplier-shop'
      preLoaderRoute: typeof AuthenticatedSupplierShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers/': {
      id: '/_authenticated/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AuthenticatedSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices/': {
      id: '/_authenticated/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof AuthenticatedDevicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/readings': {
      id: '/api/public/readings'
      path: '/api/public/readings'
      fullPath: '/api/public/readings'
      preLoaderRoute: typeof ApiPublicReadingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/irrigation/decision': {
      id: '/api/irrigation/decision'
      path: '/api/irrigation/decision'
      fullPath: '/api/irrigation/decision'
      preLoaderRoute: typeof ApiIrrigationDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commands/next': {
      id: '/api/commands/next'
      path: '/api/commands/next'
      fullPath: '/api/commands/next'
      preLoaderRoute: typeof ApiCommandsNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/advice/latest': {
      id: '/api/advice/latest'
      path: '/api/advice/latest'
      fullPath: '/api/advice/latest'
      preLoaderRoute: typeof ApiAdviceLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suppliers/$id': {
      id: '/_authenticated/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof AuthenticatedSuppliersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices/new': {
      id: '/_authenticated/devices/new'
      path: '/devices/new'
      fullPath: '/devices/new'
      preLoaderRoute: typeof AuthenticatedDevicesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices/$id': {
      id: '/_authenticated/devices/$id'
      path: '/devices/$id'
      fullPath: '/devices/$id'
      preLoaderRoute: typeof AuthenticatedDevicesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/irrigation/decision': {
      id: '/api/public/irrigation/decision'
      path: '/api/public/irrigation/decision'
      fullPath: '/api/public/irrigation/decision'
      preLoaderRoute: typeof ApiPublicIrrigationDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/devices/register': {
      id: '/api/public/devices/register'
      path: '/api/public/devices/register'
      fullPath: '/api/public/devices/register'
      preLoaderRoute: typeof ApiPublicDevicesRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/devices/ingest': {
      id: '/api/public/devices/ingest'
      path: '/api/public/devices/ingest'
      fullPath: '/api/public/devices/ingest'
      preLoaderRoute: typeof ApiPublicDevicesIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/devices/config': {
      id: '/api/public/devices/config'
      path: '/api/public/devices/config'
      fullPath: '/api/public/devices/config'
      preLoaderRoute: typeof ApiPublicDevicesConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/devices/commands': {
      id: '/api/public/devices/commands'
      path: '/api/public/devices/commands'
      fullPath: '/api/public/devices/commands'
      preLoaderRoute: typeof ApiPublicDevicesCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/devices/ack': {
      id: '/api/public/devices/ack'
      path: '/api/public/devices/ack'
      fullPath: '/api/public/devices/ack'
      preLoaderRoute: typeof ApiPublicDevicesAckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/commands/next': {
      id: '/api/public/commands/next'
      path: '/api/public/commands/next'
      fullPath: '/api/public/commands/next'
      preLoaderRoute: typeof ApiPublicCommandsNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/advice/latest': {
      id: '/api/public/advice/latest'
      path: '/api/public/advice/latest'
      fullPath: '/api/public/advice/latest'
      preLoaderRoute: typeof ApiPublicAdviceLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupplierShopRoute: typeof AuthenticatedSupplierShopRoute
  AuthenticatedDevicesIdRoute: typeof AuthenticatedDevicesIdRoute
  AuthenticatedDevicesNewRoute: typeof AuthenticatedDevicesNewRoute
  AuthenticatedSuppliersIdRoute: typeof AuthenticatedSuppliersIdRoute
  AuthenticatedDevicesIndexRoute: typeof AuthenticatedDevicesIndexRoute
  AuthenticatedSuppliersIndexRoute: typeof AuthenticatedSuppliersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupplierShopRoute: AuthenticatedSupplierShopRoute,
  AuthenticatedDevicesIdRoute: AuthenticatedDevicesIdRoute,
  AuthenticatedDevicesNewRoute: AuthenticatedDevicesNewRoute,
  AuthenticatedSuppliersIdRoute: AuthenticatedSuppliersIdRoute,
  AuthenticatedDevicesIndexRoute: AuthenticatedDevicesIndexRoute,
  AuthenticatedSuppliersIndexRoute: AuthenticatedSuppliersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiReadingsRoute: ApiReadingsRoute,
  ApiAdviceLatestRoute: ApiAdviceLatestRoute,
  ApiCommandsNextRoute: ApiCommandsNextRoute,
  ApiIrrigationDecisionRoute: ApiIrrigationDecisionRoute,
  ApiPublicReadingsRoute: ApiPublicReadingsRoute,
  ApiPublicAdviceLatestRoute: ApiPublicAdviceLatestRoute,
  ApiPublicCommandsNextRoute: ApiPublicCommandsNextRoute,
  ApiPublicDevicesAckRoute: ApiPublicDevicesAckRoute,
  ApiPublicDevicesCommandsRoute: ApiPublicDevicesCommandsRoute,
  ApiPublicDevicesConfigRoute: ApiPublicDevicesConfigRoute,
  ApiPublicDevicesIngestRoute: ApiPublicDevicesIngestRoute,
  ApiPublicDevicesRegisterRoute: ApiPublicDevicesRegisterRoute,
  ApiPublicIrrigationDecisionRoute: ApiPublicIrrigationDecisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
