// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

const SESSION_REFRESH_WINDOW_MS = 2 * 60 * 1000;

function shouldRefreshSession(expiresAt?: number | null) {
  if (!expiresAt) return false;
  return expiresAt * 1000 - Date.now() <= SESSION_REFRESH_WINDOW_MS;
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession();
    let session = data.session;

    if (session && shouldRefreshSession(session.expires_at)) {
      const refreshed = await supabase.auth.refreshSession();
      session = refreshed.data.session ?? session;
    }

    const token = session?.access_token;
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
